# Generated by Django 3.2.9 on 2022-08-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locofint',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='continente',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locofint',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.city'),
        ),
        migrations.AlterField(
            model_name='locofint',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locofint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
